Plain text and tagged text not rendering on the same line in html
opensafely-core/airlock pull request #731
Opened 2024-12-31 10:06 UTC by Providence-o

#723 

After adding `{% load markdownify %} ` at the top of `templates/file_browser/request/filegroup.html` and changing                        `{{ comment.comment }}` to `{{ comment.comment|markdownify }}` on line 59, the comments are not being displayed on the same line on the web page. 

Additional code supporting `filegroup.html` is in `assets/templates/_components/list-group/list-group-rich-item.html`
![Screenshot from 2024-12-31 09-58-40](https://github.com/user-attachments/assets/990dd86e-fbbc-4f56-91d0-98da34ea865d)

On inspecting the element in the browser:
![Screenshot from 2024-12-31 09-58-28](https://github.com/user-attachments/assets/835b83c2-5236-4792-bb71-aac0e3e548a5)

2025-01-03 11:20 UTC, inglesp approved these changes
Code changes all look good!

Please could you squash all the commits into one before merging?

2025-01-07 10:21 UTC, rebkwok requested changes
The documentation itself looks good, but I'd like to take the screenshots with the playwright tests in the same way that we do for other docs screenshots.

Can you also move the markdown comments docs to a page in the reference section, and link to it in both the researcher and output-checker how-tos. Currently it's in the output-checker docs, but the screenshots are actually from a researcher (output-checkers have the option to make comments public or private). I think it's fine to use the researcher view because it's simpler, but formatting comments isn't really part of the how-to respond/how-to review information.

The playwright tests that take screenshots are at `tests/function/test_docs_screenshots.py`.  They don't run by default locally, because they're slow, and they'll take lots of new screenshots because of the request ID and dates changing, and we only want to do that if we're actually needing to update screenshots. You can run them with:
```
RUN_SCREENSHOT_TESTS=1 just test tests/functional/test_docs_screenshots.py
```

They run headless by default, so you won't see anything happening. When you're writing new tests, it's useful to see what the browser is doing, so you can use the `--headed --slowmo 200` options and you'll see the browser open and run through the pages, button clicking etc (slowmo is in ms, and isn't required, but without it everything goes a bit too fast to see)

I'd suggest making a new test for the markdown comments rather than putting it in the big test that walks through end to end.  You'll need to set up the test with a release request and log in as the author, and then you can make it go directly to the group page and add/screenshot the comments you need.

It can be a bit fiddly to screenshot the right thing; here's a version that I think is mostly doing the right thing for one comment. It'll save the two screenshots to the docs/screenshots folder as `markdown_comment_bold_1.png` and `markdown_comment_bold_2.png`.

```
@pytest.mark.skipif(
    os.getenv("RUN_SCREENSHOT_TESTS") is None,
    reason="screenshot tests skipped; set RUN_SCREENSHOT_TESTS env variable",
)
def test_screenshot_comments(page, context, live_server):
    author, user_dicts = get_user_data()

    release_request = factories.create_request_at_status(
        "my-workspace",
        author=author,
        status=RequestStatus.RETURNED,
        files=[factories.request_file(approved=True)],
    )
    # Log in as author
    login_as_user(live_server, context, user_dicts["author"])

    # Go to group
    page.goto(live_server.url + release_request.get_url(UrlPath("group")))

    # Locators for comment elements
    comment_button = page.get_by_role("button", name=re.compile(r"^Comment"))
    comment_input = page.locator("#id_comment")
    add_comment_element = page.locator('label:has-text("Add Comment")').locator('..')
    
    # Add markdown comments
    def add_comment(comment_text, filename):
        # Fill the comment input element with the markdown text
        comment_input.fill(comment_text)
        # Screenshot before submitting
        add_comment_element.screenshot(path=settings.SCREENSHOT_DIR / f"{filename}_1.png")
        comment_button.click()

        # get the parent li element for the last submitted comment
        # we can't just use the comment_text, because it will be different in the rendered comment
        all_comments = page.locator("li.group.comment_public")
        last_comment = all_comments.nth(len(all_comments.all()) - 1)
        last_comment.scroll_into_view_if_needed()
        # The rendered comment is a bit wide for displaying side by side with the pre-submitted
        # version, so crop it to 50% of its actual width
        screenshot_element_with_padding(
            page, last_comment, f"{filename}_2.png", extra={"y": 10}, crop={"width": 0.5}
        )

    add_comment("This is **a bold comment**", "markdown_comment_bold")
    ```

2025-01-08 11:45 UTC, rebkwok approved these changes
Minor suggestion on docs wording, otherwise lgtm

2025-01-08 11:45 UTC, rebkwok commented on docs/how-tos/respond-to-returned-request.md
I'd suggest adding a separate line about formatting, with the link, so it's more obvious e.g.

"You can [write your comments in markdown](...) for additional formatting."

2025-01-08 11:45 UTC, rebkwok commented on docs/how-tos/review-a-request.md
> +the file browser. Enter your comment text, [format it as needed](../reference/formatting-comments.md), and click Save.
Same suggestion here

2025-01-08 15:17 UTC, merged